"""
Pydantic data models for the content publishing system.

All data flowing through the system is represented by these typed models.
This ensures validation, serialization, and clear contracts between layers.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


# ── Enums ────────────────────────────────────────────────────────────────────

class PublishMode(str, Enum):
    DRAFT_ONLY = "draft_only"
    REVIEW_REQUIRED = "review_required"
    PUBLISH_NOW = "publish_now"


class ApprovalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    NOT_REQUIRED = "not_required"


class Platform(str, Enum):
    INSTAGRAM = "instagram"
    SNAPCHAT = "snapchat"
    PINTEREST = "pinterest"
    TIKTOK = "tiktok"
    YOUTUBE = "youtube"
    BLOGGER = "blogger"
    MEDIUM = "medium"
    QUORA = "quora"
    REDDIT = "reddit"
    TWITTER = "twitter"
    LINKEDIN = "linkedin"
    FACEBOOK = "facebook"


class PublishStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    PUBLISHED = "published"
    DRAFT_CREATED = "draft_created"
    FAILED = "failed"
    SKIPPED = "skipped"
    REVIEW_REQUIRED = "review_required"


class ValidationSeverity(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


# ── Core Models ──────────────────────────────────────────────────────────────

class ContentPackage(BaseModel):
    """
    The master content package uploaded by the user.
    This is the single source of truth that gets adapted for each platform.
    """
    content_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    campaign_name: str = ""
    title: str = ""
    long_body: str = ""
    short_caption: str = ""
    cta: str = ""
    links: list[str] = Field(default_factory=list)
    hashtags: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    uploaded_assets: list[str] = Field(default_factory=list)  # file paths
    target_platforms: list[Platform] = Field(default_factory=list)
    publish_mode: PublishMode = PublishMode.DRAFT_ONLY
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    scheduled_time: Optional[datetime] = None
    owner: str = ""
    notes: str = ""


class PlatformPayload(BaseModel):
    """
    Adapted content for a specific platform.
    Generated by platform adapters from the master ContentPackage.
    """
    platform: Platform
    content_id: str
    title: str = ""
    body: str = ""
    caption: str = ""
    hashtags: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    links: list[str] = Field(default_factory=list)
    cta: str = ""
    media_paths: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    def summary(self) -> str:
        """Return a brief text summary of this payload for audit display."""
        parts = []
        if self.title:
            parts.append(f"Title: {self.title[:80]}")
        text = self.body or self.caption
        if text:
            parts.append(f"Body: {text[:120]}...")
        if self.hashtags:
            parts.append(f"Hashtags: {', '.join(self.hashtags[:5])}")
        return " | ".join(parts) if parts else "(empty payload)"


class PublishResult(BaseModel):
    """
    Result of a single platform publish attempt.
    """
    content_id: str
    platform: Platform
    status: PublishStatus
    draft_or_published: str = "draft"
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    variant_summary: str = ""
    url: Optional[str] = None
    error_message: Optional[str] = None
    retryable: bool = False
    notes: str = ""
    raw_response: Optional[dict[str, Any]] = None


class ValidationIssue(BaseModel):
    """A single validation finding."""
    field: str
    message: str
    severity: ValidationSeverity = ValidationSeverity.ERROR
    platform: Optional[Platform] = None


class ValidationResult(BaseModel):
    """Aggregated validation result for a content package."""
    is_valid: bool
    issues: list[ValidationIssue] = Field(default_factory=list)

    @property
    def errors(self) -> list[ValidationIssue]:
        return [i for i in self.issues if i.severity == ValidationSeverity.ERROR]

    @property
    def warnings(self) -> list[ValidationIssue]:
        return [i for i in self.issues if i.severity == ValidationSeverity.WARNING]


class AuditReport(BaseModel):
    """
    Full execution report for a publishing run.
    Persisted to SQLite and displayed in the Streamlit UI.
    """
    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    content_id: str
    campaign_name: str = ""
    publish_mode: PublishMode
    total_platforms: int = 0
    succeeded: int = 0
    failed: int = 0
    drafts: int = 0
    skipped: int = 0
    results: list[PublishResult] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None
    notes: str = ""
